### PR TITLE
Create customer login

### PR DESCRIPTION
**Pull request by GilbertCherrie**
Fixed lots of registration / login issues and customized dashboard to account type.

### CODE REVIEW

**Review by rachelj1098 — COMMENTED** [review]
It looks good and is working well! Wow, you did this so fast. One question: should a not logged in customer be able to go to the quote request and appointments pages? I think clicking those pages from the navbar when not logged in should redirect them to login. Or just not have them there. Thoughts? Otherwise its good and i think it can be pushed.

**Comment by GilbertCherrie** [comment]
Yeah, you're right not really sure what we should do here. Not sure if maybe we want to allow them to go to the page and log in once they actually try to do something on those pages or not show them the pages to begin with.

**Comment by aggarwal-h** [comment]
@GilbertCherrie Is this ready to be merged?

**Comment by GilbertCherrie** [comment]
@aggarwal-h Yeah

**Comment by aggarwal-h** [comment]
@GilbertCherrie Alright. I'll merge this.

**Pull request merged**
