### PR TITLE
Quote Comments + Desktop/Tablet styling of pages

### LINKED ISSUE #154: Add a way for Shop Owners and Customers to communicate
Some ways this can be achieved:
- a way to chat?
- a way to comment on a Quote?

### PR DESCRIPTION
**Pull request by aggarwal-h**
Closes #154.

- Adds Quote Comment
- Fixes styling of pages for Desktops/Tablets

### CODE REVIEW

**Comment by aggarwal-h** [comment]
@tevisdoe This PR adds Quote Comments (both backend and frontend). If you navigate to a Quote in the frontend, you will see an option to add comments at the bottom. 

I have made the components very modular so if we need to extend this feature to Quote Requests or other components, it should be straight forward.

Let me know if you have any suggestions!

**Comment by aggarwal-h** [comment]
This PR initially started for adding Quote Comments. But I have now added some fixes for the style of the dashboard for large screens. For instance, this is before and after:

**Before**:
Screenshot 2023-03-12 at 12 38 27 PM


**After:**
Screenshot 2023-03-12 at 12 37 56 PM

**Review by tevisdoe — APPROVED** [review]
Tried out these changes, and they work as intended. Styling looks good, and the comments are working.

One thing that I'm not sure how much I like is the fact that the comments use the username of the user. Customers might be using whatever they want as a username, not knowing it will show up in their comments, as we don't currently use it anywhere else in the app afaik (maybe on the customer profile page?). I would change this to show the name of the customer and either the name of the shop or the name of the employee/shop owner.

That's just personal preference though, and I'm fine with merging this as-is if we have more important things to do, so I'm approving.

**Comment by aggarwal-h** [comment]
> Tried out these changes, and they work as intended. Styling looks good, and the comments are working.
> 
> One thing that I'm not sure how much I like is the fact that the comments use the username of the user. Customers might be using whatever they want as a username, not knowing it will show up in their comments, as we don't currently use it anywhere else in the app afaik (maybe on the customer profile page?). I would change this to show the name of the customer and either the name of the shop or the name of the employee/shop owner.
> 
> That's just personal preference though, and I'm fine with merging this as-is if we have more important things to do, so I'm approving.

Yeah, I see your point. But first and last name are optional fields in the backend. So, if the user does not have them filled, it creates a problem in the frontend. So I just decided to use their username. One improvement I will make in the future is add a small tag beside it that says if they are customer, employee or shop owners.

**Pull request merged**
