### PR TITLE
Add relevant fields to Quote Requests, image model

### LINKED ISSUE #100: Finish Quote + Quote Request Models
Adding stuff like images to it.

### PR DESCRIPTION
**Pull request by tevisdoe**
This still need some work.

Closes #100.

### CODE REVIEW

**Comment by tevisdoe** [comment]
@aggarwal-h Hey, pinging you on this cuz we're gonna start proper development again soon. I'm not entirely sure if this is the best way to implement image storage. Have you ever done it before? Any advice? A lot of the guides I read wanted to provide a form to auto place images on the page, but I'm not sure if that's exactly what we want.

**Comment by aggarwal-h** [comment]
> @aggarwal-h Hey, pinging you on this cuz we're gonna start proper development again soon. I'm not entirely sure if this is the best way to implement image storage. Have you ever done it before? Any advice? A lot of the guides I read wanted to provide a form to auto place images on the page, but I'm not sure if that's exactly what we want.

@tevisdoe I haven't dealt with images before, but I think the best approach is described here (it uses a library called Pillow): https://www.geeksforgeeks.org/imagefield-django-models/

Here is a video on this as well: https://www.youtube.com/watch?v=V2zaeqFSSTE

Let me know if you have any trouble with it.

**Comment by tevisdoe** [comment]
@aggarwal-h I think I've got it all working. For now I'm having django serve the images itself, and our front-end can just grab them from it. I added the usual endpoints + a way to filter images via the quote request they are tied too. Could you please give it a shot?

**Review by aggarwal-h — APPROVED** [review]
@tevisdoe This looks good to me! 

The only thing I would suggest is adding is an API endpoint that lets you create a QuoteRequest and add images at the same time. Currently, the frontend app will have to first send a POST request to create a QuoteRequest. And then, using the ID of that, they will need to send another request to add the Image. It would be easier if all of this could be done in one go. 

You will need to use atomic transactions for this. I did something similar for Appointments here: https://github.com/HKanwal/kapstone/blob/59-appointments-backend/src/django-app/shops/views.py#L75-L142

But this work can be done in another PR, so I'm approving this PR.

**Pull request merged**
