### PR TITLE
13 initialize front end project

### PR DESCRIPTION
**Pull request by HKanwal**
See #13

### CODE REVIEW

**Comment by aggarwal-h** [comment]
@HKanwal This looks good. But you will need to configure two things:
1. For NextJS, you will need to add the `next-pwa` package. (https://www.npmjs.com/package/next-pwa)
2. For Django, you will need to install Django Rest Framework (https://www.django-rest-framework.org/#installation)

Also, it will be great if we can use `yarn` instead of `npm`. In my experience, `yarn` works a lot better.

**Comment by aggarwal-h** [comment]
@HKanwal Some other things I noticed: 
- the `twisted-iocpsupport==1.0.2` package in `requirements.txt` is Windows specific. It causes an error on Linux/Mac systems. You should probably state this in the `readme.md` file.
- you have configured Django to use a sqlite database. Are we using Sqlite for this project? Or PostgreSQL? (I don't know much about Sqlite). 
- the way you have configured Django is different from what I had thought initially. You are rendering the NextJS app inside of the Django app (meaning that NextJS frontend lives inside of Django). This approach is fine but we don't need this for this project. It is better for other circumstances. The code I am referring to here is in `views.py` file here: https://github.com/HKanwal/kapstone/blob/13-initialize-front-end-and-back-end-projects/src/django_server/app/views.py#L7-L8
Instead, what we want are two apps that run separately. Django will just run as the backend rest framework (and will render no page). And NextJS will be hosted separately and will run as our frontend.

**Comment by HKanwal** [comment]
Switching over to your recommended architecture. I will only initialize the nextjs project for now and leave the Django setup to you.

**Comment by HKanwal** [comment]
Missing 32x32 and 16x16 icons, so it is not installable.

**Review by aggarwal-h — APPROVED** [review]
Apart from the missing icons, this looks good!

**Pull request merged**
